apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: component-python-library
    description: Example Backstage Component Python Library
    annotations:
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: pep8speaks-org/pep8speaks
    tags:
        - python
    links:
        - url: https://colorlib.com/wp/free-dashboard-templates/
          title: Admin Dashboard
          icon: dashboard
          type: admin-dashboard
spec:
    type: service
    lifecycle: production
    owner: idpadmins
    system: project-x

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
    name: system-project-x
    description: Handy tools to keep artists in the loop
spec:
    owner: sharathkapilavai
    domain: aiml
